# SonarQube Project Configuration
sonar.host.url=http://localhost:9000
sonar.projectKey=nicocaz.com
sonar.projectName=nicocaz.com
sonar.projectVersion=1.0

# Path to the source directories
sonar.sources=src

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Exclude third-party libraries, build files, and test files from main analysis
sonar.exclusions=node_modules/**, .svelte-kit/**, build/**, public/**, *.config.js, *.config.ts
